version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
        auth:
          username: $DOCKER_ID
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/sites-packages
      - run:
          name: "install dependencies"
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: "Test application"
          command: |
            python manage.py test
